### ISSUE TITLE
[FEATURE] Migration to TypeScript

### ISSUE THREAD

**Issue by vatsalsinghkv** [vatsalsinghkv/easy-fix#5]
### Tasks to perform

- Install TypeScript
- Add path variables in `tsconfig` such that: `@` for '/src/' and `~` for '/public/'
- Migrate `src/containers/*.jsx` to `*.tsx`,
- Change import path to include `@` & `~`. Example`@/components/*.jsx`

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by akartis-dev** [comment]
> I am happy to pick this issue up if it is still available. :)

We can do it together

**Comment by hitesh-wadile** [comment]
Hey @vatsalsinghkv,

I have picked this issue for my Hacktoberfest. If it is still available to solved, I can work on it.

**Comment by vatsalsinghkv** [comment]
Hey @hitesh-wadile, this issue is already assigned to other developers. If you're really interested in migration to type-script I will create another issue for the other part of the code for migration

**Comment by hitesh-wadile** [comment]
It will be Great, if you create another issue. I will definitely work on it. Thank You.

**Comment by vatsalsinghkv** [comment]
#10 Complete

**Comment by fekete965** [comment]
@vatsalsinghkv you have assigned this issue to me initially. It is not nice and unfair of you to allow 10 people to work on a single issue as somebody like myself who has a family and a child to support won't be able to "instantly" make a PR just because I have very little free time....

**Comment by vatsalsinghkv** [comment]
@fekete965 sorry my bad, you can pull the changes and migrate the `containers/*.jsx` to tsx

**Comment by vatsalsinghkv** [comment]
@fekete965 how's the progress?

**Comment by fekete965** [comment]
@vatsalsinghkv I've made a PR to accommodate the requested changes #33 
I am happy to pick up any issues that cover TS migration.
I am also happy to improve `UrlProvider` in a separate issue.

**Comment by vatsalsinghkv** [comment]
@fekete965 you can create an issue for URLProvider, I'd love to know what are you proposing we can create a Provider component which will have all the providers

**Comment by fekete965** [comment]
@vatsalsinghkv this is the issue: https://github.com/vatsalsinghkv/easy-fix/issues/35
